changes to protected create
Gemme-Fatale/nomadda pull request #17
Opened 2022-08-24 21:48 UTC by pkamano

2022-08-24 22:11 UTC, elysemontano requested changes
Left some comments

2022-08-24 22:11 UTC, elysemontano commented on app/javascript/components/App.js
> +    console.log("mytrips", mytrips)
Let's remove this console log

2022-08-24 22:11 UTC, elysemontano commented on app/javascript/components/pages/UserCreate.js
> +  console.log("state", this.state)
Let's remove this as well

2022-08-24 22:11 UTC, elysemontano commented on app/javascript/components/pages/UserCreate.js
> +        {/* <FormGroup>
Please remove commented out code

2022-08-26 16:44 UTC, triciasykes approved these changes

2022-08-26 16:57 UTC, merged